"""Repository ports (protocols) the Providers application layer depends
on. Same rationale as `app.modules.onboarding.domain.repositories`:
services depend on these Protocols, never on `infrastructure.repositories`
directly, so unit tests can substitute fakes/mocks for the database.
"""

from __future__ import annotations

import datetime
import uuid
from typing import Protocol

from app.modules.providers.domain.models import (
    MedicalSpeciality,
    Provider,
    ProviderAffiliation,
    ProviderExternalIdentifier,
    ProviderLanguage,
    ProviderLocation,
    ProviderProfessionalRegistration,
    ProviderProfileMedia,
    ProviderPublicationHistory,
    ProviderQualification,
    ProviderService,
    ProviderSpeciality,
    ProviderStatusHistory,
    ProviderVisibilitySettings,
)


class ProviderRepository(Protocol):
    async def add(self, provider: Provider) -> None: ...
    async def get_by_id(self, provider_id: uuid.UUID) -> Provider | None: ...
    async def get_by_id_for_update(self, provider_id: uuid.UUID) -> Provider | None: ...
    async def get_by_user_id(self, user_id: uuid.UUID, provider_type: str | None = None) -> Provider | None: ...
    async def get_by_slug(self, slug: str) -> Provider | None: ...
    async def slug_exists(self, slug: str) -> bool: ...
    async def search(
        self,
        *,
        provider_type: str | None,
        verification_status: str | None,
        profile_status: str | None,
        publication_status: str | None,
        speciality_id: uuid.UUID | None,
        institution_id: uuid.UUID | None,
        registration_number: str | None,
        name: str | None,
        page: int,
        size: int,
        sort: str | None,
    ) -> tuple[list[Provider], int]: ...

    async def add_status_history(self, entry: ProviderStatusHistory) -> None: ...
    async def list_status_history(self, provider_id: uuid.UUID) -> list[ProviderStatusHistory]: ...

    async def add_publication_history(self, entry: ProviderPublicationHistory) -> None: ...
    async def list_publication_history(self, provider_id: uuid.UUID) -> list[ProviderPublicationHistory]: ...

    async def add_visibility_settings(self, settings: ProviderVisibilitySettings) -> None: ...
    async def get_visibility_settings(self, provider_id: uuid.UUID) -> ProviderVisibilitySettings | None: ...


class RegistrationRepository(Protocol):
    async def add(self, registration: ProviderProfessionalRegistration) -> None: ...
    async def get_by_id(self, registration_id: uuid.UUID) -> ProviderProfessionalRegistration | None: ...
    async def list_for_provider(self, provider_id: uuid.UUID) -> list[ProviderProfessionalRegistration]: ...
    async def get_active_primary(self, provider_id: uuid.UUID) -> ProviderProfessionalRegistration | None: ...
    async def find_by_reference(
        self, country: str, authority: str, number: str
    ) -> ProviderProfessionalRegistration | None: ...
    async def list_expiring(
        self, target_date: datetime.date
    ) -> list[ProviderProfessionalRegistration]: ...
    async def flush(self) -> None:
        """Forces pending changes to hit the database now, mid-service-
        method. Needed by `set_primary`-style "clear the old one, then set
        the new one" flows: without an intermediate flush, SQLAlchemy's
        unit-of-work doesn't guarantee the CLEAR update is emitted before
        the SET update within the same flush, which can transiently
        violate the partial unique index (two `is_primary=TRUE` rows at
        once) even though the end state is valid.
        """
        ...


class QualificationRepository(Protocol):
    async def add(self, qualification: ProviderQualification) -> None: ...
    async def get_by_id(self, qualification_id: uuid.UUID) -> ProviderQualification | None: ...
    async def list_for_provider(self, provider_id: uuid.UUID) -> list[ProviderQualification]: ...


class SpecialityRepository(Protocol):
    # Reference data (medical_specialities).
    async def get_reference_by_id(self, speciality_id: uuid.UUID) -> MedicalSpeciality | None: ...
    async def get_reference_by_code(self, code: str) -> MedicalSpeciality | None: ...
    async def list_reference(
        self, *, provider_type: str | None, parent_code: str | None, active: bool | None
    ) -> list[MedicalSpeciality]: ...
    async def add_reference(self, speciality: MedicalSpeciality) -> None: ...

    # Provider assignments (provider_specialities).
    async def add(self, assignment: ProviderSpeciality) -> None: ...
    async def get_by_id(self, provider_speciality_id: uuid.UUID) -> ProviderSpeciality | None: ...
    async def list_for_provider(self, provider_id: uuid.UUID) -> list[ProviderSpeciality]: ...
    async def get_primary(self, provider_id: uuid.UUID) -> ProviderSpeciality | None: ...
    async def get_assignment(self, provider_id: uuid.UUID, speciality_id: uuid.UUID) -> ProviderSpeciality | None: ...
    async def flush(self) -> None: ...  # see RegistrationRepository.flush's docstring


class LanguageRepository(Protocol):
    async def add(self, language: ProviderLanguage) -> None: ...
    async def get(self, provider_id: uuid.UUID, language_code: str) -> ProviderLanguage | None: ...
    async def list_for_provider(self, provider_id: uuid.UUID) -> list[ProviderLanguage]: ...
    async def delete(self, language: ProviderLanguage) -> None: ...


class ServiceRepository(Protocol):
    async def add(self, service: ProviderService) -> None: ...
    async def get_by_id(self, service_id: uuid.UUID) -> ProviderService | None: ...
    async def list_for_provider(
        self,
        provider_id: uuid.UUID,
        *,
        status: str | None = None,
        delivery_mode: str | None = None,
        pro_bono: bool | None = None,
        speciality_id: uuid.UUID | None = None,
    ) -> list[ProviderService]: ...
    async def code_exists(self, provider_id: uuid.UUID, service_code: str, *, exclude_id: uuid.UUID | None = None) -> bool: ...

    async def list_modes(self, service_id: uuid.UUID) -> list[str]: ...
    async def replace_modes(self, service_id: uuid.UUID, modes: list[str]) -> None: ...


class LocationRepository(Protocol):
    async def add(self, location: ProviderLocation) -> None: ...
    async def get_by_id(self, location_id: uuid.UUID) -> ProviderLocation | None: ...
    async def list_for_provider(self, provider_id: uuid.UUID, *, active_only: bool = False) -> list[ProviderLocation]: ...
    async def get_primary(self, provider_id: uuid.UUID) -> ProviderLocation | None: ...
    async def count_active_physical(self, provider_id: uuid.UUID) -> int: ...
    async def flush(self) -> None: ...  # see RegistrationRepository.flush's docstring


class AffiliationRepository(Protocol):
    async def add(self, affiliation: ProviderAffiliation) -> None: ...
    async def get_by_id(self, affiliation_id: uuid.UUID) -> ProviderAffiliation | None: ...
    async def list_for_provider(self, provider_id: uuid.UUID) -> list[ProviderAffiliation]: ...
    async def find_active(
        self, provider_id: uuid.UUID, institution_id: uuid.UUID, department_id: uuid.UUID | None, affiliation_type: str
    ) -> ProviderAffiliation | None: ...


class MediaRepository(Protocol):
    async def add(self, media: ProviderProfileMedia) -> None: ...
    async def get_by_id(self, media_id: uuid.UUID) -> ProviderProfileMedia | None: ...
    async def get_active(self, provider_id: uuid.UUID, media_type: str) -> ProviderProfileMedia | None: ...
    async def deactivate_others(self, provider_id: uuid.UUID, media_type: str, keep_id: uuid.UUID) -> None: ...


class ExternalIdentifierRepository(Protocol):
    async def add(self, identifier: ProviderExternalIdentifier) -> None: ...
    async def list_for_provider(self, provider_id: uuid.UUID) -> list[ProviderExternalIdentifier]: ...


class OutboxRepository(Protocol):
    async def enqueue(
        self,
        event_type: str,
        payload: dict,
        *,
        aggregate_id: uuid.UUID | None = None,
        aggregate_type: str = "Provider",
    ) -> None: ...
