"""Shared pytest fixtures.

Test isolation strategy: a dedicated `health_platform_test`
database, migrated once per test session, then truncated before every
individual test (fast enough for this table count, and simpler/more
robust than trying to share a single DB transaction across the app's
per-request session-per-dependency pattern). Roles/permissions are
re-seeded after each truncate since they live in the same database.
"""

from __future__ import annotations

import contextlib
import io
import os
import subprocess
import sys
from pathlib import Path

import pytest
from httpx import ASGITransport, AsyncClient
from sqlalchemy import text

BACKEND_DIR = Path(__file__).resolve().parent.parent

# --- Environment must be set before any `app.*` module is imported -------
os.environ.setdefault(
    "DATABASE_URL",
    "postgresql+asyncpg://health_platform:health_platform_dev@localhost:5432/health_platform_test",
)
os.environ.setdefault("TOKEN_HASH_PEPPER", "test-only-token-hash-pepper-not-for-production")
os.environ.setdefault("MFA_ENCRYPTION_KEY", "5XrovQS2SxdhwLPOrPktJLWiq1UTCSxrhDmUof5aj4Q=")
os.environ.setdefault("ENVIRONMENT", "test")
os.environ.setdefault("FRONTEND_BASE_URL", "http://localhost:3000")

# Keys generated by scripts/generate_jwt_keys.py must already exist for
# tests to import the app (see backend/README.md "Running the tests").

from app.core.database import Base, get_engine, get_session_factory  # noqa: E402
from app.core.rate_limit import get_rate_limiter  # noqa: E402
from app.main import app as fastapi_app  # noqa: E402
from app.modules.identity.domain.models import EventOutbox  # noqa: E402
from scripts.seed_document_requirements import seed as seed_document_requirements  # noqa: E402
from scripts.seed_roles_permissions import seed as seed_roles_permissions  # noqa: E402


@pytest.fixture(scope="session", autouse=True)
def _ensure_test_database_exists():
    """Creates the test database and applies migrations once per test
    session by shelling out to `createdb`/alembic — simplest reliable way
    to guarantee a clean, migrated schema before any test runs.
    """
    db_name = "health_platform_test"
    subprocess.run(
        ["createdb", "-U", "health_platform", "-h", "localhost", db_name],
        env={**os.environ, "PGPASSWORD": "health_platform_dev"},
        capture_output=True,
    )  # ignore failure if it already exists

    result = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=str(BACKEND_DIR),
        env={**os.environ},
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr)
        raise RuntimeError("Alembic migration failed for test database")
    yield


@pytest.fixture(autouse=True)
async def _clean_database():
    """Truncates every application table and re-seeds roles/permissions
    before each test, and resets the in-memory rate limiter so one test's
    failed attempts can't bleed into the next.
    """
    engine = get_engine()
    table_names = [t.name for t in Base.metadata.sorted_tables]
    async with engine.begin() as conn:
        await conn.execute(text(f"TRUNCATE {', '.join(table_names)} RESTART IDENTITY CASCADE"))

    get_rate_limiter().reset()
    with contextlib.redirect_stdout(io.StringIO()):
        await seed_roles_permissions()
        await seed_document_requirements()
    yield


@pytest.fixture
async def client():
    transport = ASGITransport(app=fastapi_app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac


@pytest.fixture
def session_factory():
    return get_session_factory()


async def get_outbox_param(session_factory, destination: str, event_type: str, param_key: str) -> str | None:
    """Test helper: pulls a raw secret (verification token / OTP code) out
    of the outbox, standing in for "the user reading the email/SMS they
    received" since these tests don't have a real inbox to check.
    """
    from sqlalchemy import select

    async with session_factory() as session:
        stmt = (
            select(EventOutbox)
            .where(EventOutbox.event_type == event_type)
            .order_by(EventOutbox.created_at.desc())
        )
        rows = (await session.execute(stmt)).scalars().all()
        for row in rows:
            payload = row.payload or {}
            if payload.get("destination") == destination:
                return payload.get("parameters", {}).get(param_key)
    return None


PATIENT_PAYLOAD = {
    "email": "ana.test@example.com",
    "password": "SecurePassword@123",
    "mobileNumber": "+258841234567",
    "firstName": "Ana",
    "lastName": "Mabote",
    "dateOfBirth": "1992-08-15",
    "termsAccepted": True,
    "privacyPolicyAccepted": True,
    "healthDataConsentAccepted": True,
}


def patient_payload(**overrides) -> dict:
    return {**PATIENT_PAYLOAD, **overrides}


# --- Onboarding test helpers -----------------------------------------------
#
# Onboarding tests need users with specific Identity roles/permissions
# (reviewers, approvers) without going through the full registration/MFA
# flow — these helpers create a user directly and mint a token for them,
# the same shortcut Identity's own admin/role tests use.

_ONBOARDING_COUNTER = {"n": 0}


async def make_user_with_role(session_factory, role_code: str, *, email: str | None = None, mobile: str | None = None):
    """Creates an ACTIVE, verified user with one active role. Returns the
    user's id.
    """
    from sqlalchemy import select

    from app.modules.identity.domain.models import Role, User, UserRole

    _ONBOARDING_COUNTER["n"] += 1
    n = _ONBOARDING_COUNTER["n"]
    email = email or f"onboarding-test-{n}@example.com"
    mobile = mobile or f"+2588{40000000 + n}"

    async with session_factory() as session:
        user = User(
            email=email,
            mobile_number=mobile,
            password_hash="x",
            account_status="ACTIVE",
            email_verified=True,
            mobile_verified=True,
        )
        session.add(user)
        await session.flush()
        role = (await session.execute(select(Role).where(Role.code == role_code))).scalar_one()
        session.add(UserRole(user_id=user.id, role_id=role.id, active=True))
        await session.commit()
        return user.id


async def token_for(user_id, roles: list[str], permissions: list[str]) -> str:
    from app.core.config import get_settings
    from app.modules.identity.application.tokens import AccessTokenCodec

    codec = AccessTokenCodec(get_settings())
    token, _ = codec.build_and_sign(
        user_id=user_id,
        session_id=user_id,
        roles=roles,
        permissions=permissions,
        email_verified=True,
        mobile_verified=True,
        mfa_verified=False,
        token_version=1,
    )
    return token


def auth_header(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}


# Permission bundles matching scripts/seed_roles_permissions.py's role grants.
ONBOARDING_APPLICANT_PERMISSIONS = [
    "ONBOARDING_APPLICATION_READ_SELF",
    "ONBOARDING_APPLICATION_UPDATE_SELF",
    "ONBOARDING_APPLICATION_SUBMIT_SELF",
    "ONBOARDING_DOCUMENT_MANAGE_SELF",
    "ONBOARDING_APPLICATION_WITHDRAW_SELF",
    "ONBOARDING_INFORMATION_REQUEST_READ_SELF",
    "ONBOARDING_INFORMATION_REQUEST_RESPOND_SELF",
]
ONBOARDING_REVIEWER_PERMISSIONS = [
    "ONBOARDING_APPLICATION_SEARCH",
    "ONBOARDING_APPLICATION_READ",
    "ONBOARDING_APPLICATION_ASSIGN",
    "ONBOARDING_APPLICATION_CLAIM",
    "ONBOARDING_REVIEW_START",
    "ONBOARDING_CHECKLIST_UPDATE",
    "ONBOARDING_DOCUMENT_REVIEW",
    "ONBOARDING_VERIFICATION_EXECUTE",
    "ONBOARDING_INFORMATION_REQUEST",
    "ONBOARDING_REVIEW_COMPLETE",
    "ONBOARDING_RISK_FLAG_MANAGE",
]
ONBOARDING_APPROVER_PERMISSIONS = ONBOARDING_REVIEWER_PERMISSIONS + [
    "ONBOARDING_APPLICATION_APPROVE",
    "ONBOARDING_APPLICATION_CONDITIONALLY_APPROVE",
    "ONBOARDING_APPLICATION_REJECT",
    "ONBOARDING_APPLICANT_SUSPEND",
    "ONBOARDING_APPLICANT_REINSTATE",
]

DOCTOR_SECTION_PAYLOADS = {
    "PERSONAL_INFORMATION": {
        "fullName": "Ana Mabote",
        "dateOfBirth": "1990-01-01",
        "nationalIdNumber": "ID-0001",
        "address": "123 Main St",
    },
    "PROFESSIONAL_REGISTRATION": {
        "registrationNumber": "OM-2026-001",
        "registrationAuthority": "Ordem dos Medicos",
        "registrationCountry": "MZ",
        "issueDate": "2020-01-01",
    },
    "QUALIFICATIONS": {"highestQualification": "MD", "institution": "University of Maputo"},
    "DECLARATIONS": {"informationAccuracyConfirmed": True, "codeOfConductAccepted": True},
}

DOCTOR_MANDATORY_DOCUMENTS = [
    "NATIONAL_ID",
    "MEDICAL_COUNCIL_CERTIFICATE",
    "GRADUATION_CERTIFICATE",
    "CURRICULUM_VITAE",
    "PROFILE_PHOTO",
    "PROFESSIONAL_LICENCE",
    "PROFESSIONAL_INDEMNITY_CERTIFICATE",
]


async def fill_doctor_application_sections(client, headers: dict) -> None:
    for section, payload in DOCTOR_SECTION_PAYLOADS.items():
        r = await client.put(f"/api/v1/onboarding/me/application/sections/{section}", json=payload, headers=headers)
        assert r.status_code == 200, r.text


async def upload_doctor_documents(client, headers: dict) -> None:
    for document_type in DOCTOR_MANDATORY_DOCUMENTS:
        mime = "image/jpeg" if document_type == "PROFILE_PHOTO" else "application/pdf"
        r = await client.post(
            "/api/v1/onboarding/me/application/documents/upload-request",
            json={"documentType": document_type, "fileName": f"{document_type}.pdf", "mimeType": mime, "fileSize": 1000},
            headers=headers,
        )
        assert r.status_code == 200, r.text
        application_document_id = r.json()["data"]["applicationDocumentId"]
        r2 = await client.post(
            f"/api/v1/onboarding/me/application/documents/{application_document_id}/confirm",
            json={
                "checksum": "abc123",
                "documentNumber": "DOC-1",
                "issuingAuthority": "Authority",
                "issuingCountry": "MZ",
                "issueDate": "2020-01-01",
                "expiryDate": "2030-01-01",
            },
            headers=headers,
        )
        assert r2.status_code == 200, r2.text


async def create_complete_doctor_application(client, applicant_token: str) -> dict:
    """Creates a fully-complete-but-not-yet-submitted DOCTOR application
    for the given applicant token. Returns the application summary dict.
    """
    headers = auth_header(applicant_token)
    r = await client.post(
        "/api/v1/onboarding/me/application", json={"applicantType": "DOCTOR", "fullName": "Ana Mabote"}, headers=headers
    )
    assert r.status_code == 200, r.text
    await fill_doctor_application_sections(client, headers)
    await upload_doctor_documents(client, headers)
    return r.json()["data"]
