"""Repository ports (protocols) the Onboarding application layer depends
on. Same rationale as `app.modules.identity.domain.repositories`:
services depend on these Protocols, never on `infrastructure.repositories`
directly, so unit tests can substitute fakes/mocks for the database.
"""

from __future__ import annotations

import datetime
import uuid
from typing import Protocol

from app.modules.onboarding.domain.models import (
    OnboardingApplication,
    OnboardingApplicationAssignment,
    OnboardingApplicationDocument,
    OnboardingApplicationNote,
    OnboardingApplicationParty,
    OnboardingApplicationSection,
    OnboardingApplicationStatusHistory,
    OnboardingDecision,
    OnboardingDocumentRequirement,
    OnboardingDocumentReview,
    OnboardingInformationRequest,
    OnboardingInformationRequestItem,
    OnboardingReverificationCase,
    OnboardingReview,
    OnboardingReviewChecklist,
    OnboardingReviewChecklistItem,
    OnboardingRiskFlag,
    OnboardingVerificationCheck,
)


class ApplicationRepository(Protocol):
    async def add(self, application: OnboardingApplication) -> None: ...
    async def get_by_id(self, application_id: uuid.UUID) -> OnboardingApplication | None: ...
    async def get_by_id_for_update(self, application_id: uuid.UUID) -> OnboardingApplication | None: ...
    async def get_by_application_number(self, application_number: str) -> OnboardingApplication | None: ...
    async def find_open_application(
        self, applicant_type: str, applicant_entity_id: uuid.UUID, purpose: str
    ) -> OnboardingApplication | None: ...
    async def find_current_application(
        self, applicant_user_id: uuid.UUID, applicant_type: str | None
    ) -> OnboardingApplication | None: ...
    async def search(
        self,
        *,
        applicant_type: str | None,
        status: str | None,
        application_number: str | None,
        assigned_reviewer_id: uuid.UUID | None,
        unassigned: bool | None,
        submitted_from: datetime.date | None,
        submitted_to: datetime.date | None,
        page: int,
        size: int,
    ) -> tuple[list[OnboardingApplication], int]: ...
    async def next_sequence_number(self, applicant_type: str, year: int) -> int: ...

    async def add_party(self, party: OnboardingApplicationParty) -> None: ...
    async def list_parties(self, application_id: uuid.UUID) -> list[OnboardingApplicationParty]: ...

    async def add_section(self, section: OnboardingApplicationSection) -> None: ...
    async def get_section(
        self, application_id: uuid.UUID, section_code: str
    ) -> OnboardingApplicationSection | None: ...
    async def list_sections(self, application_id: uuid.UUID) -> list[OnboardingApplicationSection]: ...

    async def add_status_history(self, entry: OnboardingApplicationStatusHistory) -> None: ...
    async def list_status_history(
        self, application_id: uuid.UUID
    ) -> list[OnboardingApplicationStatusHistory]: ...

    async def add_note(self, note: OnboardingApplicationNote) -> None: ...
    async def list_notes(self, application_id: uuid.UUID) -> list[OnboardingApplicationNote]: ...


class DocumentRequirementRepository(Protocol):
    async def list_applicable(
        self, applicant_type: str, application_purpose: str, country_code: str | None
    ) -> list[OnboardingDocumentRequirement]: ...
    async def get_by_id(self, requirement_id: uuid.UUID) -> OnboardingDocumentRequirement | None: ...
    async def add(self, requirement: OnboardingDocumentRequirement) -> None: ...


class ApplicationDocumentRepository(Protocol):
    async def add(self, document: OnboardingApplicationDocument) -> None: ...
    async def get_by_id(self, application_document_id: uuid.UUID) -> OnboardingApplicationDocument | None: ...
    async def list_current(self, application_id: uuid.UUID) -> list[OnboardingApplicationDocument]: ...

    async def add_review(self, review: OnboardingDocumentReview) -> None: ...
    async def list_reviews(self, application_document_id: uuid.UUID) -> list[OnboardingDocumentReview]: ...


class AssignmentRepository(Protocol):
    async def add(self, assignment: OnboardingApplicationAssignment) -> None: ...
    async def get_active_primary(
        self, application_id: uuid.UUID
    ) -> OnboardingApplicationAssignment | None: ...
    async def list_active(self, application_id: uuid.UUID) -> list[OnboardingApplicationAssignment]: ...
    async def list_by_reviewer(
        self, reviewer_id: uuid.UUID, active_only: bool
    ) -> list[OnboardingApplicationAssignment]: ...


class ReviewRepository(Protocol):
    async def add(self, review: OnboardingReview) -> None: ...
    async def get_by_id(self, review_id: uuid.UUID) -> OnboardingReview | None: ...
    async def get_active_for_application(
        self, application_id: uuid.UUID
    ) -> OnboardingReview | None: ...
    async def list_for_application(self, application_id: uuid.UUID) -> list[OnboardingReview]: ...

    async def find_checklist_template(
        self, applicant_type: str, review_type: str, application_purpose: str | None
    ) -> OnboardingReviewChecklist | None: ...
    async def add_checklist_template(self, template: OnboardingReviewChecklist) -> None: ...

    async def add_checklist_item(self, item: OnboardingReviewChecklistItem) -> None: ...
    async def list_checklist_items(self, review_id: uuid.UUID) -> list[OnboardingReviewChecklistItem]: ...
    async def get_checklist_item(self, item_id: uuid.UUID) -> OnboardingReviewChecklistItem | None: ...


class VerificationCheckRepository(Protocol):
    async def add(self, check: OnboardingVerificationCheck) -> None: ...
    async def get_by_id(self, check_id: uuid.UUID) -> OnboardingVerificationCheck | None: ...
    async def list_for_application(self, application_id: uuid.UUID) -> list[OnboardingVerificationCheck]: ...


class InformationRequestRepository(Protocol):
    async def add(self, request: OnboardingInformationRequest) -> None: ...
    async def get_by_id(self, request_id: uuid.UUID) -> OnboardingInformationRequest | None: ...
    async def list_for_application(
        self, application_id: uuid.UUID
    ) -> list[OnboardingInformationRequest]: ...
    async def list_open_overdue(self, as_of: datetime.date) -> list[OnboardingInformationRequest]: ...

    async def add_item(self, item: OnboardingInformationRequestItem) -> None: ...
    async def list_items(self, request_id: uuid.UUID) -> list[OnboardingInformationRequestItem]: ...


class DecisionRepository(Protocol):
    async def add(self, decision: OnboardingDecision) -> None: ...
    async def list_for_application(self, application_id: uuid.UUID) -> list[OnboardingDecision]: ...
    async def get_latest(self, application_id: uuid.UUID) -> OnboardingDecision | None: ...


class RiskFlagRepository(Protocol):
    async def add(self, flag: OnboardingRiskFlag) -> None: ...
    async def get_by_id(self, flag_id: uuid.UUID) -> OnboardingRiskFlag | None: ...
    async def list_for_application(self, application_id: uuid.UUID) -> list[OnboardingRiskFlag]: ...
    async def has_unresolved_blocking(self, application_id: uuid.UUID) -> bool: ...


class ReverificationRepository(Protocol):
    async def add(self, case: OnboardingReverificationCase) -> None: ...
    async def get_by_id(self, case_id: uuid.UUID) -> OnboardingReverificationCase | None: ...
    async def list_open_for_application(
        self, application_id: uuid.UUID
    ) -> list[OnboardingReverificationCase]: ...


class OutboxRepository(Protocol):
    async def enqueue(
        self,
        event_type: str,
        payload: dict,
        *,
        aggregate_id: uuid.UUID | None = None,
        aggregate_type: str = "OnboardingApplication",
    ) -> None: ...
