"""initial identity schema

Revision ID: 41eab0c36c9e
Revises: 
Create Date: 2026-07-14 08:48:15.692687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41eab0c36c9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The `email`/`provider_email` columns use PostgreSQL's case-insensitive
    # CITEXT type (spec: emails should match regardless of case). This
    # extension ships with the `postgresql-contrib` package and is not
    # enabled by default, so the migration enables it itself rather than
    # relying on manual per-database setup.
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','PROCESSED','FAILED')", name='event_outbox_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_outbox_pending', 'event_outbox', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('endpoint', sa.String(length=150), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_idempotency_endpoint_key', 'idempotency_keys', ['endpoint', 'idempotency_key'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('mobile_number', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('account_status', sa.String(length=40), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.BigInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("account_status IN ('PENDING_VERIFICATION','ACTIVE','LOCKED','SUSPENDED','DEACTIVATED','DELETED')", name='users_status_check'),
    sa.CheckConstraint('email IS NOT NULL OR mobile_number IS NOT NULL', name='users_identifier_required'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_status', 'users', ['account_status'], unique=False)
    op.create_index('ux_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ux_users_mobile', 'users', ['mobile_number'], unique=True, postgresql_where=sa.text('mobile_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('authentication_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', postgresql.CITEXT(), nullable=True),
    sa.Column('provider_email_verified', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('LOCAL','GOOGLE','APPLE','FACEBOOK')", name='authentication_provider_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='ux_authentication_provider_subject')
    )
    op.create_index('ix_authentication_identities_user', 'authentication_identities', ['user_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('identifier_hash', sa.String(length=255), nullable=True),
    sa.Column('identifier_type', sa.String(length=30), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=80), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('SUCCESS','FAILURE','BLOCKED','MFA_REQUIRED')", name='login_attempt_outcome_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_identifier', 'login_attempts', ['identifier_hash', 'occurred_at'], unique=False)
    op.create_index('ix_login_attempts_ip_time', 'login_attempts', ['ip_address', 'occurred_at'], unique=False)
    op.create_index('ix_login_attempts_user_time', 'login_attempts', ['user_id', 'occurred_at'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_history_user', 'password_history', ['user_id', 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_mfa_methods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('destination_encrypted', sa.Text(), nullable=True),
    sa.Column('destination_masked', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('AUTHENTICATOR','SMS','EMAIL')", name='user_mfa_method_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_mfa_active', 'user_mfa_methods', ['user_id'], unique=False, postgresql_where=sa.text('enabled = TRUE AND disabled_at IS NULL'))
    op.create_index('ux_user_primary_mfa', 'user_mfa_methods', ['user_id'], unique=True, postgresql_where=sa.text('is_primary = TRUE AND enabled = TRUE AND disabled_at IS NULL'))
    op.create_table('user_recovery_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_recovery_codes_active', 'user_recovery_codes', ['user_id'], unique=False, postgresql_where=sa.text('used_at IS NULL AND invalidated_at IS NULL'))
    op.create_index('ux_user_recovery_code_hash', 'user_recovery_codes', ['code_hash'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='ux_user_role')
    )
    op.create_index('ix_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_active', 'user_roles', ['user_id', 'active'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('device_platform', sa.String(length=40), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=120), nullable=True),
    sa.Column('parent_session_id', sa.UUID(), nullable=True),
    sa.Column('replaced_by_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("device_platform IS NULL OR device_platform IN ('WEB','IOS','ANDROID','OTHER')", name='user_session_platform_check'),
    sa.ForeignKeyConstraint(['parent_session_id'], ['user_sessions.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['user_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_token_family', 'user_sessions', ['token_family_id'], unique=False)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ux_user_sessions_refresh_hash', 'user_sessions', ['refresh_token_hash'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("token_type IN ('EMAIL_VERIFICATION','MOBILE_OTP','PASSWORD_RESET','MFA_CHALLENGE','EMAIL_CHANGE','MOBILE_CHANGE')", name='verification_token_type_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_tokens_active', 'verification_tokens', ['user_id', 'token_type', 'expires_at'], unique=False, postgresql_where=sa.text('used_at IS NULL AND invalidated_at IS NULL'))
    op.create_index('ux_verification_token_hash', 'verification_tokens', ['token_hash'], unique=True)
    op.create_table('identity_security_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')", name='identity_security_severity_check'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_identity_security_severity', 'identity_security_events', ['severity', 'created_at'], unique=False)
    op.create_index('ix_identity_security_user', 'identity_security_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identity_security_user', table_name='identity_security_events')
    op.drop_index('ix_identity_security_severity', table_name='identity_security_events')
    op.drop_table('identity_security_events')
    op.drop_index('ux_verification_token_hash', table_name='verification_tokens')
    op.drop_index('ix_verification_tokens_active', table_name='verification_tokens', postgresql_where=sa.text('used_at IS NULL AND invalidated_at IS NULL'))
    op.drop_table('verification_tokens')
    op.drop_index('ux_user_sessions_refresh_hash', table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_user_sessions_token_family', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_roles_user_active', table_name='user_roles')
    op.drop_index('ix_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ux_user_recovery_code_hash', table_name='user_recovery_codes')
    op.drop_index('ix_user_recovery_codes_active', table_name='user_recovery_codes', postgresql_where=sa.text('used_at IS NULL AND invalidated_at IS NULL'))
    op.drop_table('user_recovery_codes')
    op.drop_index('ux_user_primary_mfa', table_name='user_mfa_methods', postgresql_where=sa.text('is_primary = TRUE AND enabled = TRUE AND disabled_at IS NULL'))
    op.drop_index('ix_user_mfa_active', table_name='user_mfa_methods', postgresql_where=sa.text('enabled = TRUE AND disabled_at IS NULL'))
    op.drop_table('user_mfa_methods')
    op.drop_table('role_permissions')
    op.drop_index('ix_password_history_user', table_name='password_history')
    op.drop_table('password_history')
    op.drop_index('ix_login_attempts_user_time', table_name='login_attempts')
    op.drop_index('ix_login_attempts_ip_time', table_name='login_attempts')
    op.drop_index('ix_login_attempts_identifier', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('ix_authentication_identities_user', table_name='authentication_identities')
    op.drop_table('authentication_identities')
    op.drop_index('ux_users_mobile', table_name='users', postgresql_where=sa.text('mobile_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ux_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('ux_idempotency_endpoint_key', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_event_outbox_pending', table_name='event_outbox', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('event_outbox')
    # ### end Alembic commands ###

    op.execute('DROP EXTENSION IF EXISTS citext')
