"""onboarding module schema

Revision ID: 4eefc4fbb15e
Revises: 41eab0c36c9e
Create Date: 2026-07-16 09:00:40.536666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eefc4fbb15e'
down_revision: Union[str, Sequence[str], None] = '41eab0c36c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_number', sa.String(length=60), nullable=False),
    sa.Column('applicant_type', sa.String(length=50), nullable=False),
    sa.Column('applicant_user_id', sa.UUID(), nullable=False),
    sa.Column('applicant_entity_id', sa.UUID(), nullable=False),
    sa.Column('application_purpose', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('submission_version', sa.Integer(), nullable=False),
    sa.Column('current_reviewer_id', sa.UUID(), nullable=True),
    sa.Column('current_approval_level', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_level_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_level_paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_paused_seconds', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("applicant_type IN ('DOCTOR','NUTRITIONIST','HOSPITAL','CLINIC','PHARMACY')", name='onboarding_applicant_type_check'),
    sa.CheckConstraint("application_purpose IN ('INITIAL_ONBOARDING','PERIODIC_REVERIFICATION','CREDENTIAL_RENEWAL','PROFILE_MATERIAL_CHANGE','REINSTATEMENT')", name='onboarding_purpose_check'),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','QUEUED','UNDER_REVIEW','ADDITIONAL_INFORMATION_REQUIRED','RESUBMITTED','PENDING_SECOND_LEVEL_REVIEW','PENDING_APPROVAL','APPROVED','CONDITIONALLY_APPROVED','REJECTED','WITHDRAWN','EXPIRED','SUSPENDED','REINSTATEMENT_REQUIRED','CANCELLED')", name='onboarding_status_check'),
    sa.CheckConstraint('completion_percentage BETWEEN 0 AND 100', name='onboarding_completion_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_index('ix_onboarding_applications_applicant', 'onboarding_applications', ['applicant_type', 'applicant_entity_id'], unique=False)
    op.create_index('ix_onboarding_applications_reviewer', 'onboarding_applications', ['current_reviewer_id', 'status'], unique=False)
    op.create_index('ix_onboarding_applications_sla', 'onboarding_applications', ['service_level_due_at'], unique=False, postgresql_where=sa.text("status IN ('SUBMITTED','QUEUED','UNDER_REVIEW','PENDING_APPROVAL')"))
    op.create_index('ix_onboarding_applications_status', 'onboarding_applications', ['status', 'submitted_at'], unique=False)
    op.create_index('ux_onboarding_open_application', 'onboarding_applications', ['applicant_type', 'applicant_entity_id', 'application_purpose'], unique=True, postgresql_where=sa.text("status IN ('DRAFT','SUBMITTED','QUEUED','UNDER_REVIEW','ADDITIONAL_INFORMATION_REQUIRED','RESUBMITTED','PENDING_SECOND_LEVEL_REVIEW','PENDING_APPROVAL')"))
    op.create_table('onboarding_document_requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_type', sa.String(length=50), nullable=False),
    sa.Column('application_purpose', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('speciality_code', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('minimum_quantity', sa.Integer(), nullable=False),
    sa.Column('maximum_quantity', sa.Integer(), nullable=False),
    sa.Column('requires_issue_date', sa.Boolean(), nullable=False),
    sa.Column('requires_expiry_date', sa.Boolean(), nullable=False),
    sa.Column('requires_document_number', sa.Boolean(), nullable=False),
    sa.Column('requires_issuing_authority', sa.Boolean(), nullable=False),
    sa.Column('allowed_mime_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('maximum_file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_document_requirements', 'onboarding_document_requirements', ['applicant_type', 'application_purpose', 'active'], unique=False)
    op.create_table('onboarding_event_outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','PROCESSED','FAILED')", name='onboarding_event_outbox_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_event_outbox_pending', 'onboarding_event_outbox', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('onboarding_review_checklists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_type', sa.String(length=50), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('application_purpose', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_checklists_lookup', 'onboarding_review_checklists', ['applicant_type', 'review_type', 'active'], unique=False)
    op.create_table('onboarding_application_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("assignment_type IN ('PRIMARY_REVIEW','SECOND_LEVEL_REVIEW','COMPLIANCE_REVIEW','FINAL_APPROVAL')", name='onboarding_assignment_type_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_assignments_application', 'onboarding_application_assignments', ['application_id', 'active'], unique=False)
    op.create_index('ix_onboarding_assignments_reviewer', 'onboarding_application_assignments', ['reviewer_id', 'active'], unique=False)
    op.create_index('ux_onboarding_active_primary_assignment', 'onboarding_application_assignments', ['application_id'], unique=True, postgresql_where=sa.text("active = TRUE AND assignment_type = 'PRIMARY_REVIEW'"))
    op.create_table('onboarding_application_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_number', sa.String(length=180), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('issuing_country', sa.String(length=2), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('satisfies_requirement_id', sa.UUID(), nullable=True),
    sa.Column('current_version', sa.Boolean(), nullable=False),
    sa.Column('supersedes_application_document_id', sa.UUID(), nullable=True),
    sa.Column('locked_by_decision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("processing_status IN ('PENDING_UPLOAD','UPLOADED','PROCESSING','AVAILABLE','REJECTED','SUPERSEDED','DELETED')", name='onboarding_document_processing_check'),
    sa.CheckConstraint("review_status IN ('PENDING','ACCEPTED','REJECTED','CLARIFICATION_REQUIRED','EXPIRED','UNVERIFIABLE')", name='onboarding_document_review_check'),
    sa.CheckConstraint('expiry_date IS NULL OR issue_date IS NULL OR expiry_date >= issue_date', name='onboarding_document_dates_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.ForeignKeyConstraint(['satisfies_requirement_id'], ['onboarding_document_requirements.id'], ),
    sa.ForeignKeyConstraint(['supersedes_application_document_id'], ['onboarding_application_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_documents_application', 'onboarding_application_documents', ['application_id', 'current_version'], unique=False)
    op.create_index('ix_onboarding_documents_expiry', 'onboarding_application_documents', ['expiry_date'], unique=False, postgresql_where=sa.text('expiry_date IS NOT NULL AND current_version = TRUE'))
    op.create_table('onboarding_application_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_notes_application', 'onboarding_application_notes', ['application_id', 'created_at'], unique=False)
    op.create_table('onboarding_application_parties',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('party_type', sa.String(length=60), nullable=False),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('organisation_name', sa.String(length=255), nullable=True),
    sa.Column('identity_number_encrypted', sa.Text(), nullable=True),
    sa.Column('identity_number_hash', sa.String(length=255), nullable=True),
    sa.Column('ownership_percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("party_type IN ('PRIMARY_APPLICANT','AUTHORISED_REPRESENTATIVE','DIRECTOR','OWNER','BENEFICIAL_OWNER','RESPONSIBLE_PROFESSIONAL','ADMINISTRATOR')", name='onboarding_party_type_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_parties_application', 'onboarding_application_parties', ['application_id'], unique=False)
    op.create_table('onboarding_application_sections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('section_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED','IN_PROGRESS','COMPLETE','INVALID','NOT_APPLICABLE')", name='onboarding_section_status_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'section_code', name='ux_onboarding_application_section')
    )
    op.create_index('ix_onboarding_sections_application', 'onboarding_application_sections', ['application_id'], unique=False)
    op.create_table('onboarding_application_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.String(length=60), nullable=True),
    sa.Column('new_status', sa.String(length=60), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_status_history', 'onboarding_application_status_history', ['application_id', 'created_at'], unique=False)
    op.create_table('onboarding_decisions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('decision_by', sa.UUID(), nullable=False),
    sa.Column('decision_comments', sa.Text(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('approval_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_new_application', sa.Boolean(), nullable=True),
    sa.Column('cooling_off_period_days', sa.Integer(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supersedes_decision_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision_type IN ('APPROVED','CONDITIONALLY_APPROVED','REJECTED','SUSPENDED','REINSTATED','EXPIRED','ADMINISTRATIVE_CORRECTION')", name='onboarding_decision_type_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.ForeignKeyConstraint(['supersedes_decision_id'], ['onboarding_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_decisions_application', 'onboarding_decisions', ['application_id', 'created_at'], unique=False)
    op.create_table('onboarding_information_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('response_due_date', sa.Date(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','PARTIALLY_RESPONDED','RESPONDED','SATISFIED','CLOSED','OVERDUE','CANCELLED')", name='onboarding_information_request_status_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_information_requests', 'onboarding_information_requests', ['application_id', 'status'], unique=False)
    op.create_table('onboarding_reverification_cases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('original_application_id', sa.UUID(), nullable=False),
    sa.Column('resulting_application_id', sa.UUID(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=60), nullable=False),
    sa.Column('trigger_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OPEN','APPLICATION_CREATED','RESOLVED','CANCELLED')", name='onboarding_reverification_status_check'),
    sa.CheckConstraint("trigger_reason IN ('APPROACHING_EXPIRY','DOCUMENT_REPLACED','LICENCE_RENEWED','MATERIAL_CHANGE','COMPLIANCE_REQUEST')", name='onboarding_reverification_trigger_check'),
    sa.ForeignKeyConstraint(['original_application_id'], ['onboarding_applications.id'], ),
    sa.ForeignKeyConstraint(['resulting_application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_reverification_original', 'onboarding_reverification_cases', ['original_application_id'], unique=False)
    op.create_table('onboarding_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recommendation', sa.String(length=40), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("recommendation IS NULL OR recommendation IN ('APPROVE','CONDITIONAL_APPROVAL','REJECT','REQUEST_INFORMATION','ESCALATE')", name='onboarding_review_recommendation_check'),
    sa.CheckConstraint("review_type IN ('INITIAL_REVIEW','DOCUMENT_REVIEW','COMPLIANCE_REVIEW','PROFESSIONAL_VERIFICATION','SECOND_LEVEL_REVIEW','FINAL_APPROVAL','REVERIFICATION_REVIEW')", name='onboarding_review_type_check'),
    sa.CheckConstraint("status IN ('IN_PROGRESS','COMPLETED','CANCELLED')", name='onboarding_review_status_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_reviews_application', 'onboarding_reviews', ['application_id'], unique=False)
    op.create_index('ix_onboarding_reviews_reviewer', 'onboarding_reviews', ['reviewer_id', 'status'], unique=False)
    op.create_table('onboarding_risk_flags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('flag_code', sa.String(length=120), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution_comments', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='onboarding_risk_level_check'),
    sa.CheckConstraint("status IN ('OPEN','UNDER_REVIEW','RESOLVED','ACCEPTED','DISMISSED')", name='onboarding_risk_status_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_risk_application', 'onboarding_risk_flags', ['application_id', 'status'], unique=False)
    op.create_table('onboarding_verification_checks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('subject_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=True),
    sa.Column('external_request_id', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("result IS NULL OR result IN ('MATCH','PARTIAL_MATCH','NO_MATCH','NOT_FOUND','UNAVAILABLE','FAILED','MANUAL_REVIEW_REQUIRED')", name='onboarding_verification_result_check'),
    sa.CheckConstraint("status IN ('PENDING','IN_PROGRESS','COMPLETED','FAILED','CANCELLED')", name='onboarding_verification_status_check'),
    sa.ForeignKeyConstraint(['application_id'], ['onboarding_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_verification_application', 'onboarding_verification_checks', ['application_id'], unique=False)
    op.create_index('ix_onboarding_verification_retry', 'onboarding_verification_checks', ['status', 'next_retry_at'], unique=False, postgresql_where=sa.text("status = 'FAILED'"))
    op.create_table('onboarding_document_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_document_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('verification_method', sa.String(length=80), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('verified_document_number', sa.String(length=180), nullable=True),
    sa.Column('verified_expiry_date', sa.Date(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('ACCEPTED','REJECTED','CLARIFICATION_REQUIRED','EXPIRED','UNVERIFIABLE')", name='onboarding_document_review_decision_check'),
    sa.ForeignKeyConstraint(['application_document_id'], ['onboarding_application_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_document_reviews_document', 'onboarding_document_reviews', ['application_document_id', 'created_at'], unique=False)
    op.create_table('onboarding_information_request_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('information_request_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('field_name', sa.String(length=150), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_reference', sa.String(length=255), nullable=True),
    sa.Column('satisfied_by', sa.UUID(), nullable=True),
    sa.Column('satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("item_type IN ('DOCUMENT','FIELD','DECLARATION','EXPLANATION','OTHER')", name='onboarding_information_item_type_check'),
    sa.CheckConstraint("status IN ('OPEN','RESPONDED','SATISFIED','REJECTED')", name='onboarding_information_item_status_check'),
    sa.ForeignKeyConstraint(['information_request_id'], ['onboarding_information_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_information_items_request', 'onboarding_information_request_items', ['information_request_id'], unique=False)
    op.create_table('onboarding_review_checklist_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=120), nullable=False),
    sa.Column('item_description', sa.String(length=500), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("result IN ('NOT_REVIEWED','PASS','FAIL','NOT_APPLICABLE','CLARIFICATION_REQUIRED')", name='onboarding_checklist_result_check'),
    sa.ForeignKeyConstraint(['review_id'], ['onboarding_reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'item_code', name='ux_onboarding_review_checklist_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_review_checklist_items')
    op.drop_index('ix_onboarding_information_items_request', table_name='onboarding_information_request_items')
    op.drop_table('onboarding_information_request_items')
    op.drop_index('ix_onboarding_document_reviews_document', table_name='onboarding_document_reviews')
    op.drop_table('onboarding_document_reviews')
    op.drop_index('ix_onboarding_verification_retry', table_name='onboarding_verification_checks', postgresql_where=sa.text("status = 'FAILED'"))
    op.drop_index('ix_onboarding_verification_application', table_name='onboarding_verification_checks')
    op.drop_table('onboarding_verification_checks')
    op.drop_index('ix_onboarding_risk_application', table_name='onboarding_risk_flags')
    op.drop_table('onboarding_risk_flags')
    op.drop_index('ix_onboarding_reviews_reviewer', table_name='onboarding_reviews')
    op.drop_index('ix_onboarding_reviews_application', table_name='onboarding_reviews')
    op.drop_table('onboarding_reviews')
    op.drop_index('ix_onboarding_reverification_original', table_name='onboarding_reverification_cases')
    op.drop_table('onboarding_reverification_cases')
    op.drop_index('ix_onboarding_information_requests', table_name='onboarding_information_requests')
    op.drop_table('onboarding_information_requests')
    op.drop_index('ix_onboarding_decisions_application', table_name='onboarding_decisions')
    op.drop_table('onboarding_decisions')
    op.drop_index('ix_onboarding_status_history', table_name='onboarding_application_status_history')
    op.drop_table('onboarding_application_status_history')
    op.drop_index('ix_onboarding_sections_application', table_name='onboarding_application_sections')
    op.drop_table('onboarding_application_sections')
    op.drop_index('ix_onboarding_parties_application', table_name='onboarding_application_parties')
    op.drop_table('onboarding_application_parties')
    op.drop_index('ix_onboarding_notes_application', table_name='onboarding_application_notes')
    op.drop_table('onboarding_application_notes')
    op.drop_index('ix_onboarding_documents_expiry', table_name='onboarding_application_documents', postgresql_where=sa.text('expiry_date IS NOT NULL AND current_version = TRUE'))
    op.drop_index('ix_onboarding_documents_application', table_name='onboarding_application_documents')
    op.drop_table('onboarding_application_documents')
    op.drop_index('ux_onboarding_active_primary_assignment', table_name='onboarding_application_assignments', postgresql_where=sa.text("active = TRUE AND assignment_type = 'PRIMARY_REVIEW'"))
    op.drop_index('ix_onboarding_assignments_reviewer', table_name='onboarding_application_assignments')
    op.drop_index('ix_onboarding_assignments_application', table_name='onboarding_application_assignments')
    op.drop_table('onboarding_application_assignments')
    op.drop_index('ix_onboarding_checklists_lookup', table_name='onboarding_review_checklists')
    op.drop_table('onboarding_review_checklists')
    op.drop_index('ix_onboarding_event_outbox_pending', table_name='onboarding_event_outbox', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('onboarding_event_outbox')
    op.drop_index('ix_onboarding_document_requirements', table_name='onboarding_document_requirements')
    op.drop_table('onboarding_document_requirements')
    op.drop_index('ux_onboarding_open_application', table_name='onboarding_applications', postgresql_where=sa.text("status IN ('DRAFT','SUBMITTED','QUEUED','UNDER_REVIEW','ADDITIONAL_INFORMATION_REQUIRED','RESUBMITTED','PENDING_SECOND_LEVEL_REVIEW','PENDING_APPROVAL')"))
    op.drop_index('ix_onboarding_applications_status', table_name='onboarding_applications')
    op.drop_index('ix_onboarding_applications_sla', table_name='onboarding_applications', postgresql_where=sa.text("status IN ('SUBMITTED','QUEUED','UNDER_REVIEW','PENDING_APPROVAL')"))
    op.drop_index('ix_onboarding_applications_reviewer', table_name='onboarding_applications')
    op.drop_index('ix_onboarding_applications_applicant', table_name='onboarding_applications')
    op.drop_table('onboarding_applications')
    # ### end Alembic commands ###
