"""providers module schema

Revision ID: a88ea57d63d1
Revises: 4eefc4fbb15e
Create Date: 2026-07-20 00:03:00.724776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88ea57d63d1'
down_revision: Union[str, Sequence[str], None] = '4eefc4fbb15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_specialities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('parent_speciality_id', sa.UUID(), nullable=True),
    sa.Column('requires_verified_qualification', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_speciality_id'], ['medical_specialities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_medical_specialities_type', 'medical_specialities', ['provider_type', 'active'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('professional_title', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('short_biography', sa.String(length=500), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('profile_status', sa.String(length=40), nullable=False),
    sa.Column('publication_status', sa.String(length=40), nullable=False),
    sa.Column('profile_completion_percentage', sa.Integer(), nullable=False),
    sa.Column('approval_application_id', sa.UUID(), nullable=True),
    sa.Column('approval_reference', sa.String(length=100), nullable=True),
    sa.Column('approval_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("profile_status IN ('DRAFT','INCOMPLETE','INACTIVE','ACTIVE','SUSPENDED','DEACTIVATED','ARCHIVED')", name='providers_profile_status_check'),
    sa.CheckConstraint("provider_type IN ('DOCTOR','NUTRITIONIST','DENTIST','PSYCHOLOGIST','PHYSIOTHERAPIST','NURSE','PHARMACIST','LABORATORY_PROFESSIONAL','FITNESS_PROFESSIONAL','OTHER_HEALTH_PROFESSIONAL')", name='providers_type_check'),
    sa.CheckConstraint("publication_status IN ('UNPUBLISHED','PUBLISHED','HIDDEN','REMOVED')", name='providers_publication_status_check'),
    sa.CheckConstraint("verification_status IN ('NOT_VERIFIED','PENDING','VERIFIED','CONDITIONALLY_VERIFIED','REJECTED','SUSPENDED','EXPIRED','REVOKED')", name='providers_verification_status_check'),
    sa.CheckConstraint('profile_completion_percentage BETWEEN 0 AND 100', name='providers_completion_check'),
    sa.CheckConstraint('years_of_experience IS NULL OR years_of_experience BETWEEN 0 AND 80', name='providers_experience_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_providers_status', 'providers', ['verification_status', 'profile_status', 'publication_status'], unique=False)
    op.create_index('ix_providers_type', 'providers', ['provider_type'], unique=False)
    op.create_index('ux_providers_slug', 'providers', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ux_providers_user_type', 'providers', ['user_id', 'provider_type'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('providers_event_outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','PROCESSED','FAILED')", name='providers_event_outbox_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_providers_event_outbox_pending', 'providers_event_outbox', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('provider_affiliations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('affiliation_type', sa.String(length=50), nullable=False),
    sa.Column('affiliation_source', sa.String(length=50), nullable=False),
    sa.Column('professional_position', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('ended_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("affiliation_source IN ('SELF_DECLARED','INSTITUTION_REGISTERED','BACK_OFFICE_CREATED','ONBOARDING_VERIFIED')", name='provider_affiliation_source_check'),
    sa.CheckConstraint("affiliation_type IN ('EMPLOYED','CONTRACTED','VISITING','PRACTICE_PRIVILEGES','VOLUNTEER','OWNER','DIRECTOR','OTHER')", name='provider_affiliation_type_check'),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','REJECTED','SUSPENDED','ENDED','CANCELLED')", name='provider_affiliation_status_check'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='provider_affiliation_date_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_affiliations_institution', 'provider_affiliations', ['institution_id', 'status'], unique=False)
    op.create_index('ix_provider_affiliations_provider', 'provider_affiliations', ['provider_id', 'status'], unique=False)
    op.create_table('provider_external_identifiers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('system_code', sa.String(length=100), nullable=False),
    sa.Column('external_identifier', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_code', 'external_identifier', name='ux_provider_external_identifier')
    )
    op.create_index('ix_provider_external_ids_provider', 'provider_external_identifiers', ['provider_id'], unique=False)
    op.create_table('provider_languages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('proficiency', sa.String(length=30), nullable=False),
    sa.Column('can_consult', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("proficiency IN ('BASIC','INTERMEDIATE','FLUENT','NATIVE')", name='provider_language_proficiency_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'language_code', name='ux_provider_language')
    )
    op.create_index('ix_provider_languages_search', 'provider_languages', ['language_code', 'can_consult'], unique=False)
    op.create_table('provider_locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('contact_number', sa.String(length=30), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('parking_available', sa.Boolean(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("location_type IN ('PRIVATE_PRACTICE','HOSPITAL','CLINIC','VIRTUAL','HOME_VISIT_SERVICE_AREA','OTHER')", name='provider_location_type_check'),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name='provider_location_latitude_check'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name='provider_location_longitude_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_locations_geo', 'provider_locations', ['country_code', 'province', 'city'], unique=False)
    op.create_index('ix_provider_locations_provider', 'provider_locations', ['provider_id', 'active'], unique=False)
    op.create_index('ux_provider_primary_location', 'provider_locations', ['provider_id'], unique=True, postgresql_where=sa.text("is_primary = TRUE AND active = TRUE AND deleted_at IS NULL AND location_type <> 'VIRTUAL'"))
    op.create_table('provider_professional_registrations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('registration_type', sa.String(length=80), nullable=False),
    sa.Column('registration_number', sa.String(length=180), nullable=False),
    sa.Column('registration_authority', sa.String(length=255), nullable=False),
    sa.Column('registration_country', sa.String(length=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('registration_status', sa.String(length=40), nullable=False),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('onboarding_application_id', sa.UUID(), nullable=True),
    sa.Column('verification_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('decision_locked', sa.Boolean(), nullable=False),
    sa.Column('supersedes_registration_id', sa.UUID(), nullable=True),
    sa.Column('last_expiry_reminder_window_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("registration_status IN ('ACTIVE','INACTIVE','EXPIRED','SUSPENDED','REVOKED','SUPERSEDED')", name='provider_registration_status_check'),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED','PENDING','VERIFIED','REJECTED','UNVERIFIABLE')", name='provider_registration_verification_check'),
    sa.CheckConstraint('expiry_date IS NULL OR issue_date IS NULL OR expiry_date >= issue_date', name='provider_registration_date_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['supersedes_registration_id'], ['provider_professional_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_registrations_expiry', 'provider_professional_registrations', ['expiry_date'], unique=False, postgresql_where=sa.text("expiry_date IS NOT NULL AND registration_status = 'ACTIVE'"))
    op.create_index('ix_provider_registrations_provider', 'provider_professional_registrations', ['provider_id', 'registration_status'], unique=False)
    op.create_index('ux_provider_primary_registration', 'provider_professional_registrations', ['provider_id'], unique=True, postgresql_where=sa.text("is_primary = TRUE AND deleted_at IS NULL AND registration_status = 'ACTIVE'"))
    op.create_index('ux_provider_registration_reference', 'provider_professional_registrations', ['registration_country', 'registration_authority', 'registration_number'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND registration_status <> 'SUPERSEDED'"))
    op.create_table('provider_profile_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('moderation_status', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("media_type IN ('PROFILE_PHOTO','COVER_IMAGE','INTRODUCTION_VIDEO','OTHER')", name='provider_media_type_check'),
    sa.CheckConstraint("moderation_status IN ('PENDING','APPROVED','REJECTED','NOT_REQUIRED')", name='provider_media_moderation_check'),
    sa.CheckConstraint("processing_status IN ('PENDING_UPLOAD','UPLOADED','PROCESSING','AVAILABLE','REJECTED','DELETED')", name='provider_media_processing_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_profile_media', 'provider_profile_media', ['provider_id', 'media_type', 'active'], unique=False)
    op.create_table('provider_publication_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('PUBLISHED','UNPUBLISHED','HIDDEN','RESTORED','REMOVED')", name='provider_publication_action_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_publication_history', 'provider_publication_history', ['provider_id', 'created_at'], unique=False)
    op.create_table('provider_qualifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('qualification_type', sa.String(length=60), nullable=False),
    sa.Column('qualification_name', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('institution_country', sa.String(length=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('speciality_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('onboarding_application_id', sa.UUID(), nullable=True),
    sa.Column('verification_reference', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('decision_locked', sa.Boolean(), nullable=False),
    sa.Column('supersedes_qualification_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("qualification_type IN ('UNDERGRADUATE_DEGREE','POSTGRADUATE_DEGREE','DIPLOMA','CERTIFICATE','BOARD_CERTIFICATION','SPECIALIST_QUALIFICATION','PROFESSIONAL_COURSE','OTHER')", name='provider_qualification_type_check'),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED','PENDING','VERIFIED','REJECTED','UNVERIFIABLE')", name='provider_qualification_verification_check'),
    sa.CheckConstraint('completion_date IS NULL OR start_date IS NULL OR completion_date >= start_date', name='provider_qualification_date_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['medical_specialities.id'], ),
    sa.ForeignKeyConstraint(['supersedes_qualification_id'], ['provider_qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_qualifications_provider', 'provider_qualifications', ['provider_id', 'verification_status'], unique=False)
    op.create_table('provider_services',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('speciality_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('pro_bono', sa.Boolean(), nullable=False),
    sa.Column('requires_pre_screening', sa.Boolean(), nullable=False),
    sa.Column('minimum_patient_age', sa.Integer(), nullable=True),
    sa.Column('maximum_patient_age', sa.Integer(), nullable=True),
    sa.Column('booking_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('cancellation_notice_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('publicly_visible', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','INACTIVE','SUSPENDED','ARCHIVED')", name='provider_service_status_check'),
    sa.CheckConstraint('duration_minutes BETWEEN 5 AND 480', name='provider_service_duration_check'),
    sa.CheckConstraint('effective_until IS NULL OR effective_from IS NULL OR effective_until >= effective_from', name='provider_service_effective_date_check'),
    sa.CheckConstraint('minimum_patient_age IS NULL OR maximum_patient_age IS NULL OR maximum_patient_age >= minimum_patient_age', name='provider_service_age_check'),
    sa.CheckConstraint('pro_bono = TRUE OR (price IS NOT NULL AND price >= 0 AND currency IS NOT NULL)', name='provider_service_price_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['medical_specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_services_provider', 'provider_services', ['provider_id', 'status'], unique=False)
    op.create_index('ix_provider_services_speciality', 'provider_services', ['speciality_id', 'status'], unique=False)
    op.create_index('ux_provider_service_code', 'provider_services', ['provider_id', 'service_code'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND status <> 'ARCHIVED'"))
    op.create_table('provider_specialities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('speciality_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("verification_status IN ('UNVERIFIED','PENDING','VERIFIED','REJECTED')", name='provider_speciality_verification_check'),
    sa.CheckConstraint('years_of_experience IS NULL OR years_of_experience BETWEEN 0 AND 80', name='provider_speciality_experience_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['speciality_id'], ['medical_specialities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_speciality_search', 'provider_specialities', ['speciality_id', 'verification_status'], unique=False)
    op.create_index('ux_provider_primary_speciality', 'provider_specialities', ['provider_id'], unique=True, postgresql_where=sa.text('is_primary = TRUE AND deleted_at IS NULL'))
    op.create_index('ux_provider_speciality', 'provider_specialities', ['provider_id', 'speciality_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('provider_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('status_type', sa.String(length=40), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_type IN ('VERIFICATION_STATUS','PROFILE_STATUS','PUBLICATION_STATUS')", name='provider_status_history_type_check'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_status_history', 'provider_status_history', ['provider_id', 'created_at'], unique=False)
    op.create_table('provider_visibility_settings',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('show_full_biography', sa.Boolean(), nullable=False),
    sa.Column('show_qualifications', sa.Boolean(), nullable=False),
    sa.Column('show_affiliations', sa.Boolean(), nullable=False),
    sa.Column('show_locations', sa.Boolean(), nullable=False),
    sa.Column('show_years_of_experience', sa.Boolean(), nullable=False),
    sa.Column('show_languages', sa.Boolean(), nullable=False),
    sa.Column('show_service_prices', sa.Boolean(), nullable=False),
    sa.Column('allow_direct_booking', sa.Boolean(), nullable=False),
    sa.Column('allow_pro_bono_discovery', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('provider_service_modes',
    sa.Column('provider_service_id', sa.UUID(), nullable=False),
    sa.Column('delivery_mode', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("delivery_mode IN ('VIDEO','AUDIO','SECURE_CHAT','IN_PERSON','HOME_VISIT','GROUP_SESSION')", name='provider_service_mode_check'),
    sa.ForeignKeyConstraint(['provider_service_id'], ['provider_services.id'], ),
    sa.PrimaryKeyConstraint('provider_service_id', 'delivery_mode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_service_modes')
    op.drop_table('provider_visibility_settings')
    op.drop_index('ix_provider_status_history', table_name='provider_status_history')
    op.drop_table('provider_status_history')
    op.drop_index('ux_provider_speciality', table_name='provider_specialities', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ux_provider_primary_speciality', table_name='provider_specialities', postgresql_where=sa.text('is_primary = TRUE AND deleted_at IS NULL'))
    op.drop_index('ix_provider_speciality_search', table_name='provider_specialities')
    op.drop_table('provider_specialities')
    op.drop_index('ux_provider_service_code', table_name='provider_services', postgresql_where=sa.text("deleted_at IS NULL AND status <> 'ARCHIVED'"))
    op.drop_index('ix_provider_services_speciality', table_name='provider_services')
    op.drop_index('ix_provider_services_provider', table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_index('ix_provider_qualifications_provider', table_name='provider_qualifications')
    op.drop_table('provider_qualifications')
    op.drop_index('ix_provider_publication_history', table_name='provider_publication_history')
    op.drop_table('provider_publication_history')
    op.drop_index('ix_provider_profile_media', table_name='provider_profile_media')
    op.drop_table('provider_profile_media')
    op.drop_index('ux_provider_registration_reference', table_name='provider_professional_registrations', postgresql_where=sa.text("deleted_at IS NULL AND registration_status <> 'SUPERSEDED'"))
    op.drop_index('ux_provider_primary_registration', table_name='provider_professional_registrations', postgresql_where=sa.text("is_primary = TRUE AND deleted_at IS NULL AND registration_status = 'ACTIVE'"))
    op.drop_index('ix_provider_registrations_provider', table_name='provider_professional_registrations')
    op.drop_index('ix_provider_registrations_expiry', table_name='provider_professional_registrations', postgresql_where=sa.text("expiry_date IS NOT NULL AND registration_status = 'ACTIVE'"))
    op.drop_table('provider_professional_registrations')
    op.drop_index('ux_provider_primary_location', table_name='provider_locations', postgresql_where=sa.text("is_primary = TRUE AND active = TRUE AND deleted_at IS NULL AND location_type <> 'VIRTUAL'"))
    op.drop_index('ix_provider_locations_provider', table_name='provider_locations')
    op.drop_index('ix_provider_locations_geo', table_name='provider_locations')
    op.drop_table('provider_locations')
    op.drop_index('ix_provider_languages_search', table_name='provider_languages')
    op.drop_table('provider_languages')
    op.drop_index('ix_provider_external_ids_provider', table_name='provider_external_identifiers')
    op.drop_table('provider_external_identifiers')
    op.drop_index('ix_provider_affiliations_provider', table_name='provider_affiliations')
    op.drop_index('ix_provider_affiliations_institution', table_name='provider_affiliations')
    op.drop_table('provider_affiliations')
    op.drop_index('ix_providers_event_outbox_pending', table_name='providers_event_outbox', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('providers_event_outbox')
    op.drop_index('ux_providers_user_type', table_name='providers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ux_providers_slug', table_name='providers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_providers_type', table_name='providers')
    op.drop_index('ix_providers_status', table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_medical_specialities_type', table_name='medical_specialities')
    op.drop_table('medical_specialities')
    # ### end Alembic commands ###
