"""Repository ports (protocols) the application layer depends on.

Services depend on these `Protocol`s, never on `infrastructure.repositories`
directly (dependency inversion — see spec section 3's layering rule).
This is what lets unit tests substitute fakes/`AsyncMock(spec=...)` for the
database, exactly as required by spec section 25's "Mocks or fakes should
be used for: User repository, Session repository, Token repository...".

Note on the "domain layer must not depend on ... database frameworks"
rule: the models these protocols pass around (`User`, `UserSession`, ...)
are SQLAlchemy models. This project takes the pragmatic "ORM model as
domain entity" approach rather than maintaining a parallel set of plain
dataclasses plus mappers — a common, accepted trade-off for a service of
this size. If a future need arises to truly decouple (e.g. swapping the
ORM), only `infrastructure/repositories.py` and this file's type hints
would need to change; application services never touch SQLAlchemy directly.
"""

from __future__ import annotations

import datetime
import uuid
from typing import Protocol

from app.modules.identity.domain.models import (
    AuthenticationIdentity,
    IdentitySecurityEvent,
    LoginAttempt,
    PasswordHistory,
    Role,
    User,
    UserMfaMethod,
    UserRecoveryCode,
    UserRole,
    UserSession,
    VerificationToken,
)


class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_mobile(self, mobile_number: str) -> User | None: ...
    async def add(self, user: User) -> None: ...

    async def get_auth_identity(
        self, provider: str, provider_subject: str
    ) -> AuthenticationIdentity | None: ...
    async def list_auth_identities(self, user_id: uuid.UUID) -> list[AuthenticationIdentity]: ...
    async def add_auth_identity(self, identity: AuthenticationIdentity) -> None: ...
    async def delete_auth_identity(self, identity: AuthenticationIdentity) -> None: ...

    async def add_password_history(self, entry: PasswordHistory) -> None: ...
    async def list_recent_password_hashes(self, user_id: uuid.UUID, limit: int) -> list[str]: ...


class RoleRepository(Protocol):
    async def get_role_by_code(self, code: str) -> Role | None: ...
    async def get_active_user_role(self, user_id: uuid.UUID, role_code: str) -> UserRole | None: ...
    async def list_active_user_roles(self, user_id: uuid.UUID) -> list[tuple[UserRole, Role]]: ...
    async def add_user_role(self, user_role: UserRole) -> None: ...
    async def get_effective_permissions(self, user_id: uuid.UUID) -> set[str]: ...


class SessionRepository(Protocol):
    async def add(self, session: UserSession) -> None: ...
    async def get_by_refresh_hash(self, refresh_token_hash: str) -> UserSession | None: ...
    async def get_by_id(self, session_id: uuid.UUID) -> UserSession | None: ...
    async def list_active_family_heads(self, user_id: uuid.UUID) -> list[UserSession]: ...
    async def get_family_created_at(self, token_family_id: uuid.UUID) -> datetime.datetime | None: ...
    async def revoke(self, session: UserSession, reason: str) -> None: ...
    async def revoke_all_for_user(self, user_id: uuid.UUID, reason: str) -> int: ...
    async def revoke_all_for_user_except(
        self, user_id: uuid.UUID, keep_session_id: uuid.UUID, reason: str
    ) -> int: ...
    async def revoke_family(self, token_family_id: uuid.UUID, reason: str) -> int: ...


class VerificationRepository(Protocol):
    async def add(self, token: VerificationToken) -> None: ...
    async def get_by_hash(self, token_hash: str) -> VerificationToken | None: ...
    async def get_by_id(self, token_id: uuid.UUID) -> VerificationToken | None: ...
    async def get_active_for_user(
        self, user_id: uuid.UUID, token_type: str
    ) -> VerificationToken | None: ...
    async def invalidate_active_for_user(self, user_id: uuid.UUID, token_type: str) -> None: ...


class MfaRepository(Protocol):
    async def add_method(self, method: UserMfaMethod) -> None: ...
    async def get_method_by_id(self, method_id: uuid.UUID) -> UserMfaMethod | None: ...
    async def list_enabled_methods(self, user_id: uuid.UUID) -> list[UserMfaMethod]: ...
    async def add_recovery_codes(self, codes: list[UserRecoveryCode]) -> None: ...
    async def get_recovery_code_by_hash(
        self, user_id: uuid.UUID, code_hash: str
    ) -> UserRecoveryCode | None: ...
    async def invalidate_unused_recovery_codes(self, user_id: uuid.UUID) -> None: ...


class SecurityLogRepository(Protocol):
    async def add_login_attempt(self, attempt: LoginAttempt) -> None: ...
    async def add_security_event(self, event: IdentitySecurityEvent) -> None: ...


class OutboxRepository(Protocol):
    async def enqueue(
        self,
        event_type: str,
        payload: dict,
        *,
        aggregate_id: uuid.UUID | None = None,
        aggregate_type: str = "User",
    ) -> None: ...
